const stocks = [
    { label: "Apple (AAPL)", value: "AAPL" },
    { label: "Tesla (TSLA)", value: "TSLA" },
    { label: "Amazon (AMZN)", value: "AMZN" },
    { label: "Google (GOOGL)", value: "GOOGL" },
    { label: "Microsoft (MSFT)", value: "MSFT" },
    { label: "NVIDIA (NVDA)", value: "NVDA" },
    { label: "Meta (META)", value: "META" },
    { label: "Netflix (NFLX)", value: "NFLX" },
    { label: "Adobe (ADBE)", value: "ADBE" },
    { label: "Intel (INTC)", value: "INTC" },
    { label: "AMD (AMD)", value: "AMD" },
    { label: "Salesforce (CRM)", value: "CRM" },
    { label: "PayPal (PYPL)", value: "PYPL" },
    { label: "Uber (UBER)", value: "UBER" },
    { label: "Lyft (LYFT)", value: "LYFT" },
    { label: "Zoom (ZM)", value: "ZM" },
    { label: "IBM (IBM)", value: "IBM" },
    { label: "Oracle (ORCL)", value: "ORCL" },
    { label: "Cisco (CSCO)", value: "CSCO" },
    { label: "Twitter (TWTR)", value: "TWTR" },
    { label: "Snapchat (SNAP)", value: "SNAP" },
    { label: "Spotify (SPOT)", value: "SPOT" },
    { label: "Shopify (SHOP)", value: "SHOP" },
    { label: "Square (SQ)", value: "SQ" },
    { label: "Pinterest (PINS)", value: "PINS" },
    { label: "Boeing (BA)", value: "BA" },
    { label: "Ford (F)", value: "F" },
    { label: "General Motors (GM)", value: "GM" },
    { label: "Honda (HMC)", value: "HMC" },
    { label: "Toyota (TM)", value: "TM" },
    { label: "Volkswagen (VWAGY)", value: "VWAGY" },
    { label: "Rivian (RIVN)", value: "RIVN" },
    { label: "Lucid Motors (LCID)", value: "LCID" },
    { label: "Starbucks (SBUX)", value: "SBUX" },
    { label: "McDonald's (MCD)", value: "MCD" },
    { label: "Coca-Cola (KO)", value: "KO" },
    { label: "PepsiCo (PEP)", value: "PEP" },
    { label: "Walmart (WMT)", value: "WMT" },
    { label: "Costco (COST)", value: "COST" },
    { label: "Target (TGT)", value: "TGT" },
    { label: "Home Depot (HD)", value: "HD" },
    { label: "Lowe's (LOW)", value: "LOW" },
    { label: "Nike (NKE)", value: "NKE" },
    { label: "Adidas (ADDYY)", value: "ADDYY" },
    { label: "Puma (PUMSY)", value: "PUMSY" },
    { label: "Under Armour (UAA)", value: "UAA" },
    { label: "Disney (DIS)", value: "DIS" },
    { label: "Warner Bros (WBD)", value: "WBD" },
    { label: "Paramount (PARA)", value: "PARA" },
    { label: "Sony (SONY)", value: "SONY" },
    { label: "Netflix (NFLX)", value: "NFLX" },
    { label: "Roku (ROKU)", value: "ROKU" },
    { label: "Domino's Pizza (DPZ)", value: "DPZ" },
    { label: "Papa John's (PZZA)", value: "PZZA" },
    { label: "Yum! Brands (YUM)", value: "YUM" },
    { label: "Chipotle (CMG)", value: "CMG" },
    { label: "Darden Restaurants (DRI)", value: "DRI" },
    { label: "Marriott (MAR)", value: "MAR" },
    { label: "Hilton (HLT)", value: "HLT" },
    { label: "Hyatt (H)", value: "H" },
    { label: "Delta Airlines (DAL)", value: "DAL" },
    { label: "American Airlines (AAL)", value: "AAL" },
    { label: "Southwest Airlines (LUV)", value: "LUV" },
    { label: "United Airlines (UAL)", value: "UAL" },
    { label: "JetBlue (JBLU)", value: "JBLU" },
    { label: "ExxonMobil (XOM)", value: "XOM" },
    { label: "Chevron (CVX)", value: "CVX" },
    { label: "Shell (SHEL)", value: "SHEL" },
    { label: "BP (BP)", value: "BP" },
    { label: "ConocoPhillips (COP)", value: "COP" },
    { label: "Pfizer (PFE)", value: "PFE" },
    { label: "Moderna (MRNA)", value: "MRNA" },
    { label: "Johnson & Johnson (JNJ)", value: "JNJ" },
    { label: "AstraZeneca (AZN)", value: "AZN" },
    { label: "Novavax (NVAX)", value: "NVAX" },
    { label: "Gilead Sciences (GILD)", value: "GILD" },
    { label: "AbbVie (ABBV)", value: "ABBV" },
    { label: "Eli Lilly (LLY)", value: "LLY" },
    { label: "Regeneron (REGN)", value: "REGN" },
    { label: "Biogen (BIIB)", value: "BIIB" },
    { label: "Bristol-Myers (BMY)", value: "BMY" },
    { label: "Merck (MRK)", value: "MRK" },
    { label: "3M (MMM)", value: "MMM" },
    { label: "General Electric (GE)", value: "GE" },
    { label: "Caterpillar (CAT)", value: "CAT" },
    { label: "Honeywell (HON)", value: "HON" },
    { label: "Lockheed Martin (LMT)", value: "LMT" },
    { label: "Raytheon Technologies (RTX)", value: "RTX" },
    { label: "Northrop Grumman (NOC)", value: "NOC" },
    { label: "Berkshire Hathaway (BRK.B)", value: "BRK.B" },
    { label: "JPMorgan Chase (JPM)", value: "JPM" },
    { label: "Bank of America (BAC)", value: "BAC" },
    { label: "Wells Fargo (WFC)", value: "WFC" },
    { label: "Citigroup (C)", value: "C" },
    { label: "Goldman Sachs (GS)", value: "GS" },
    { label: "Morgan Stanley (MS)", value: "MS" },
    { label: "BlackRock (BLK)", value: "BLK" },
    { label: "Visa (V)", value: "V" },
    { label: "Mastercard (MA)", value: "MA" },
    { label: "American Express (AXP)", value: "AXP" },
    { label: "Reliance Industries (RELIANCE)", value: "RELIANCE" },
    { label: "Tata Consultancy Services (TCS)", value: "TCS" },
    { label: "HDFC Bank (HDFCBANK)", value: "HDFCBANK" },
    { label: "ICICI Bank (ICICIBANK)", value: "ICICIBANK" },
    { label: "Infosys (INFY)", value: "INFY" },
    { label: "State Bank of India (SBIN)", value: "SBIN" },
    { label: "Bharti Airtel (BHARTIARTL)", value: "BHARTIARTL" },
    { label: "Kotak Mahindra Bank (KOTAKBANK)", value: "KOTAKBANK" },
    { label: "Hindustan Unilever (HINDUNILVR)", value: "HINDUNILVR" },
    { label: "ITC (ITC)", value: "ITC" },
    { label: "Asian Paints (ASIANPAINT)", value: "ASIANPAINT" },
    { label: "Larsen & Toubro (LT)", value: "LT" },
    { label: "Axis Bank (AXISBANK)", value: "AXISBANK" },
    { label: "Maruti Suzuki (MARUTI)", value: "MARUTI" },
    { label: "HCL Technologies (HCLTECH)", value: "HCLTECH" },
    { label: "Wipro (WIPRO)", value: "WIPRO" },
    { label: "Sun Pharma (SUNPHARMA)", value: "SUNPHARMA" },
    { label: "Mahindra & Mahindra (M&M)", value: "M&M" },
    { label: "Tata Motors (TATAMOTORS)", value: "TATAMOTORS" },
    { label: "UltraTech Cement (ULTRACEMCO)", value: "ULTRACEMCO" },
    { label: "Tata Steel (TATASTEEL)", value: "TATASTEEL" },
    { label: "Bajaj Finance (BAJFINANCE)", value: "BAJFINANCE" },
    { label: "Adani Enterprises (ADANIENT)", value: "ADANIENT" },
    { label: "Nestle India (NESTLEIND)", value: "NESTLEIND" },
    { label: "Power Grid Corporation (POWERGRID)", value: "POWERGRID" },
    { label: "NTPC (NTPC)", value: "NTPC" },
    { label: "Tech Mahindra (TECHM)", value: "TECHM" },
    { label: "Grasim Industries (GRASIM)", value: "GRASIM" },
    { label: "Dr Reddy's Laboratories (DRREDDY)", value: "DRREDDY" },
    { label: "IndusInd Bank (INDUSINDBK)", value: "INDUSINDBK" },
    { label: "JSW Steel (JSWSTEEL)", value: "JSWSTEEL" },
    { label: "Adani Ports (ADANIPORTS)", value: "ADANIPORTS" },
    { label: "Britannia Industries (BRITANNIA)", value: "BRITANNIA" },
    { label: "Coal India (COALINDIA)", value: "COALINDIA" },
    { label: "Eicher Motors (EICHERMOT)", value: "EICHERMOT" },
    { label: "Bajaj Auto (BAJAJ-AUTO)", value: "BAJAJ-AUTO" },
    { label: "Dabur India (DABUR)", value: "DABUR" },
    { label: "Godrej Consumer Products (GODREJCP)", value: "GODREJCP" },
    { label: "Pidilite Industries (PIDILITIND)", value: "PIDILITIND" },
    { label: "Tata Consumer Products (TATACONSUM)", value: "TATACONSUM" },
    { label: "Havells India (HAVELLS)", value: "HAVELLS" },
    { label: "Bharat Petroleum (BPCL)", value: "BPCL" },
    { label: "Indian Oil Corporation (IOC)", value: "IOC" },
    { label: "Siemens India (SIEMENS)", value: "SIEMENS" },
    { label: "ABB India (ABB)", value: "ABB" },
    { label: "GAIL India (GAIL)", value: "GAIL" },
    { label: "Bank of Baroda (BANKBARODA)", value: "BANKBARODA" },
    { label: "Canara Bank (CANBK)", value: "CANBK" },
    { label: "Union Bank of India (UNIONBANK)", value: "UNIONBANK" },
    { label: "Punjab National Bank (PNB)", value: "PNB" },
    { label: "IDFC First Bank (IDFCFIRSTB)", value: "IDFCFIRSTB" },
    { label: "SBI Life Insurance (SBILIFE)", value: "SBILIFE" },
    { label: "HDFC Life Insurance (HDFCLIFE)", value: "HDFCLIFE" },
    { label: "ICICI Prudential Life (ICICIPRULI)", value: "ICICIPRULI" },
    { label: "Bajaj Finserv (BAJAJFINSV)", value: "BAJAJFINSV" },
    { label: "Zomato (ZOMATO)", value: "ZOMATO" },
    { label: "Paytm (PAYTM)", value: "PAYTM" },
    { label: "Nykaa (NYKAA)", value: "NYKAA" },
    { label: "PolicyBazaar (POLICYBZR)", value: "POLICYBZR" },
    { label: "IRCTC (IRCTC)", value: "IRCTC" },
    { label: "Tata Power (TATAPOWER)", value: "TATAPOWER" },
    { label: "Adani Green Energy (ADANIGREEN)", value: "ADANIGREEN" },
    { label: "Adani Transmission (ADANITRANS)", value: "ADANITRANS" },
    { label: "Borosil Renewables (BORORENEW)", value: "BORORENEW" },
    { label: "Suzlon Energy (SUZLON)", value: "SUZLON" },
    { label: "Ashok Leyland (ASHOKLEY)", value: "ASHOKLEY" },
    { label: "Motherson Sumi (MOTHERSON)", value: "MOTHERSON" },
    { label: "Lupin (LUPIN)", value: "LUPIN" },
    { label: "Biocon (BIOCON)", value: "BIOCON" },
    { label: "Divi's Laboratories (DIVISLAB)", value: "DIVISLAB" },
    { label: "Torrent Pharmaceuticals (TORNTPHARM)", value: "TORNTPHARM" },
    { label: "Shree Cement (SHREECEM)", value: "SHREECEM" },
    { label: "Ambuja Cements (AMBUJACEM)", value: "AMBUJACEM" },
    { label: "ACC (ACC)", value: "ACC" },
    { label: "Hindalco (HINDALCO)", value: "HINDALCO" },
    { label: "Steel Authority of India (SAIL)", value: "SAIL" },
    { label: "GMR Infra (GMRINFRA)", value: "GMRINFRA" },
    { label: "Dixon Technologies (DIXON)", value: "DIXON" },
    { label: "L&T Infotech (LTI)", value: "LTI" },
    { label: "Mindtree (MINDTREE)", value: "MINDTREE" },
    { label: "Persistent Systems (PERSISTENT)", value: "PERSISTENT" },
    { label: "Hindustan Aeronautics (HAL)", value: "HAL" },
    { label: "BEML (BEML)", value: "BEML" },
    { label: "IRCON International (IRCON)", value: "IRCON" },
    { label: "Rail Vikas Nigam (RVNL)", value: "RVNL" },
  ];
export default stocks;  